### PR TITLE
TMDM-11244: Link the custom layout in the view.

### PR DESCRIPTION
**Pull request by sbliu**

### CODE REVIEW

**Comment by hbhong** [comment]
Validated.

**Comment by sbliu** [comment]
all the link custom form codes are in EE plugins, changes in SE code is to find such or other likeness capability, so link custom form only take into effect in EE studio, SE studio won't know and show that .

**Comment by pbabin** [comment]
OK, but you changed WS call to add an additional parameter. From my perspective, only EE webservices would be changed

**Comment by hbhong** [comment]
Validated.

**Pull request merged**
